[tool.poetry]
name = "taipan"
version = "1.0.0"
description = "Taipan is a simple imperative language inspired by Python."
authors = ["Theo Guerin"]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.5"
pyright = "^1.1.364"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
