name: CI/CD

on:
  push:
    branches:
      - release

permissions:
  contents: read

jobs:
  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: "3.12"

      - name: Test typing with pyright
        run: poetry run pyright

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: "3.12"

      - name: Lint with ruff
        run: poetry run ruff check

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: "3.12"

      - name: Run tests
        run: poetry run pytest

  deploy:
    needs: [typing, linting, testing]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/taipan-lang/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: "3.12"

      - name: Package project
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  realease:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: "3.12"

      - name: Get version
        id: version
        run: poetry version -s

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.stdout }}
